### ISSUE TITLE
dmesg on Windows

### ISSUE THREAD

**Issue by grimec** [ddvk/remarkable-uuuflash#2]
I'm trying to follow the readme but I'm not able to to run dmesg on a Windows machine.
I've tried to look for alternatives and tried "https://docs.microsoft.com/en-us/sysinternals/downloads/psloglist" with no luck.

**Comment by Eeems** [comment]
I would expect that you would run dmesg in a linux subsystem.

**Comment by ddvk** [comment]
dmesg is under linux only. under windows you may need some cdc driver as well. 

 i will have to test it, in detail

**Comment by grimec** [comment]
as there were instructions for Windows machines I thought you would have a workaround of some sort :(

**Comment by ddvk** [comment]
> as there were instructions for Windows machines I thought you would have a workaround of some sort :(

the windows addition was premature. it “should” work in theory, at least the first part works, but then the device enters “gadget” mode, and windows does not recognize it.


you can open the device manager, and look for the “unknown usb device”. under windows dmesg is the event viewer

**Comment by Eeems** [comment]
> 
> 
> dmesg is under linux only. under windows you may need some cdc driver as well.
> 
> i will have to test it, in detail

The instructions say otherwise ;)
![image](https://user-images.githubusercontent.com/1176979/79128557-f2ad5680-7d60-11ea-904b-483c6dc5b0da.png)

**Comment by ddvk** [comment]
updated the readme
