### ISSUE TITLE
update and reflash?

### ISSUE THREAD

**Issue by knuella** [ddvk/remarkable-uuuflash#3]
Hi everyone,

I have installed some additional things on my remarkable, like entware, draft and fingertherm. After a reboot it freeze at the starting screen, saying "reMarkable is starting".

I thought the device is lost, but with your recover tool I can chroot into the internal ram and maybe repair the system. Very much thanks for your work. 

I followed the posts at [bricked_my_remarkable_need_help](https://www.reddit.com/r/RemarkableTablet/comments/8x8dt4/bricked_my_remarkable_need_help/ ) but don't find the problem. I came to the point to reinstall the uboot and root, but my /boot and /var/lib/uboot is a little bit different to the posts on reddit and I worry to take a wrong Image. Unfortunately there are no logs in /var/log or journalctl after I bricked the device. 

Your tools update and reflash seems to can do that things for me, is that right? Can you please help me a little bit, as long as the doku is missing?

Here the files in /boot and /var/lib/uboot from the chroot:
```
root@rmrestore:/# ls -latr /var/lib/uboot/ /boot
/var/lib/uboot/:
drwxr-xr-x    2 root     root         16384 Jan  1  1970 .
-rwxr-xr-x    1 root     root        985543 Jan  1  1980 waveform.bin
-rwxr-xr-x    1 root     root       2629368 Apr  7 19:11 splash.bmp
-rwxr-xr-x    1 root     root        263224 Apr  7 19:11 lowbattery.bmp
drwxr-xr-x    9 root     root          1024 Apr  8 09:34 ..
-rwxr-xr-x    1 root     root          8192 Apr 29 18:38 uboot.env

/boot:
drwxr-xr-x    2 root     root          1024 Dec  5 17:39 .
-rw-r--r--    1 root     root         32600 Dec  5 18:20 zero-gravitas.dtb
-rw-r--r--    1 root     root       4203736 Dec  5 18:20 zImage-4.9.84-zero-gravitas
lrwxrwxrwx    1 root     root            27 Dec  5 18:20 zImage -> zImage-4.9.84-zero-gravitas
lrwxrwxrwx    1 root     root            17 Dec  5 18:20 devicetree-zImage-zero-gravitas.dtb -> zero-gravitas.dtb
-rw-r--r--    1 root     root        224256 Mar 20 13:25 u-boot.imx
drwxr-xr-x   19 root     root          1024 Apr 29 17:52 ..
```

Best regards
Robin

**Comment by ddvk** [comment]
did you disable the xochitl service or mess with the splash.bmp?

if you are desperate you can try: `./uuu upgrade.uuu`, which will overwrite both root partitions. if you didn't mess with the boot partition. when is says ok, the device won't reboot on it's own, you have to power off/power on manually

**Comment by knuella** [comment]
xochitl was enabled and the splash.bmp was in place.

I do `uuu upgrade.uuu` and i works fine. Good work, your little programm help me very much!
