### ISSUE TITLE
Remarkable won't boot

### ISSUE THREAD

**Issue by muke101** [ddvk/remarkable-uuuflash#7]
Hi, I hope this isn't an inappropriate place to post this, if so I'd appreciate being pointed into the right direction.

I tried to compile and install a new kernel for my remarkable 1 tablet. It's the same version with the same def config, just with a couple things changed. I did this over the serial console by replacing the `zImage` and `.dtb` files in `/boot`, while saving the original in `/home`. The remarkable failed to boot, so I suppose I misconfigured my kernel somehow, but now after accessing the remarkable again and replacing the old files in `/boot`, it still refuses to boot. Here's the current state of the `/boot` directory mounted on `/dev/mmcblk1p2`:

![image](https://user-images.githubusercontent.com/39006618/97881884-dda70d80-1d1a-11eb-9a30-69c0c69571a3.png)

I'm almost certain these are all the original files the remarkable came with. What are my options here? Can I completely reflash the system somehow? I tried running the reflash.uuu file but this doesn't appear to change anything. Any help would be appreciated, thanks.

**Comment by ddvk** [comment]
there are 2 root partitions, 2 and 3 , copy to both of them

**Comment by muke101** [comment]
partition 3 is untouched, I've only been modifying 2. They seem to have the same content, would you suggest copying over the boot partition from 3 to 2?

**Comment by ddvk** [comment]
i'm not sure the reflash.uuu was finished.

try `./uuu upgrade.uuu` this will overwrite both root partitions

also you my find more that can help on the discord chanel

**Comment by muke101** [comment]
`upgrade.uuu` has fixed it, thank you. It would be helpful if this were documented in the repo! 

Could you also please share the discord server? I'm sure I would find this helpful.

**Comment by Eeems** [comment]
> 
> 
> `upgrade.uuu` has fixed it, thank you. It would be helpful if this were documented in the repo!

You mean https://github.com/ddvk/remarkable-uuuflash#semi-upgrade-overwriting-the-root-with-version-2113 ?

> 
> Could you also please share the discord server? I'm sure I would find this helpful.

[![Discord](https://img.shields.io/discord/463752820026376202.svg?label=reMarkable&logo=discord&logoColor=ffffff&color=7389D8&labelColor=6A7EC2)](https://discord.gg/ATqQGfu)

**Comment by muke101** [comment]
The subsection says 'to be documented' so I wasn't certain what it would do, and didn't want to run it without knowing.

**Comment by Eeems** [comment]
> 
> 
> The subsection says 'to be documented' so I wasn't certain what it would do, and didn't want to run it without knowing.

The title is fairly clear about what it does though. That said, that's a good point. There is a bunch of extra documentation that should really be added at some point.
